server:
  port: 7070

spring:
  application:
    name: configserver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    config:
      server:
        git:
          uri: https://github.com/JevonYang/nacos-config-server-validate
          search-paths: /

